language: go

go:
    - 1.4
    - release
    - tip

before_install:
- go get gopkg.in/fatih/set.v0
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover

script:
- $HOME/gopath/bin/goveralls -repotoken OI6L2gZpWXiyVNP3Nf3dxZS0gjsYiGFk4
